### ISSUE TITLE
The compressed onnx model can't run inference.

### ISSUE THREAD

**Issue by rotorliu** [tianyic/only_train_once#13]
When checking the compressed model accuracy in tutorial 01, the error is as follow:

---------------------------------------------------------------------------
```
InvalidArgument                           Traceback (most recent call last)
Cell In[5], line 7
      2 testloader = torch.utils.data.DataLoader(testset, batch_size=1, shuffle=False, num_workers=4)
      4 # acc1_full, acc5_full = check_accuracy(model, testloader)
      5 # print("Full model: Acc 1: {acc1}, Acc 5: {acc5}".format(acc1=acc1_full, acc5=acc5_full))
----> 7 acc1_compressed, acc5_compressed = check_accuracy_onnx("ResNet_compressed.onnx", testloader)
      8 print("Compressed model: Acc 1: {acc1}, Acc 5: {acc5}".format(acc1=acc1_compressed, acc5=acc5_compressed))

File [e:\github\only_train_once\tutorials\utils\utils.py:57](file:///E:/github/only_train_once/tutorials/utils/utils.py:57), in check_accuracy_onnx(model_path, testloader, two_input)
     54 total = 0
     56 for X, y in testloader:
---> 57     outputs = ort_sess.run(None, {'input.1': X.numpy()})[0]
     58     prec1, prec5 = accuracy_topk(torch.tensor(outputs), y.data, topk=(1, 5))
     59     correct1 += prec1.item()

File [~\AppData\Roaming\Python\Python38\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:200](https://file+.vscode-resource.vscode-cdn.net/e%3A/github/only_train_once/tutorials/~/AppData/Roaming/Python/Python38/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:200), in Session.run(self, output_names, input_feed, run_options)
    198     output_names = [output.name for output in self._outputs_meta]
    199 try:
--> 200     return self._sess.run(output_names, input_feed, run_options)
    201 except C.EPFail as err:
    202     if self._enable_fallback:

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gemm node. Name:'Gemm_47' Status Message: GEMM: Dimension mismatch, W: {10,15} K: 512 N:10
```

**Comment by rotorliu** [comment]
![image](https://user-images.githubusercontent.com/494495/229400115-4de722c8-aaaf-4b28-8f0e-a11c3898b624.png)
ResNet_full_group_sparse model is OK!

**Comment by tianyic** [comment]
Thanks for the question @rotorliu 

Could you please share your torch, onnx and torch version?

Since I do not reproduce such issue on my environments, here are the normal full and compressed models should look like. You could find the [checkpoints](https://drive.google.com/drive/folders/1lZ7Wsehi0hr_g8nztbAFEJIhF8C4Q8Kp?usp=share_link).  

![image](https://user-images.githubusercontent.com/8930611/229401107-c2a1f036-0585-4053-ae38-3519ce80503b.png)
![image](https://user-images.githubusercontent.com/8930611/229401171-0ae77a7d-ae85-446f-b027-528d0f406d2b.png)

![image](https://user-images.githubusercontent.com/8930611/229401569-0a195719-fa76-4eac-bab7-8c57cb6219e1.png)

**Comment by rotorliu** [comment]
Python 3.8.13
torch 1.10.2
onnx 1.14.0

**Comment by rotorliu** [comment]
Yes，My compressed onnx is only different from the full model at the end of model (Gemm node). So I think the result is wrong.

**Comment by tianyic** [comment]
Thanks for sharing your configs @rotorliu . Will test it out next week, if such configs does not work on my end either, I will update the requirements file and proceed a fix. 

Here are my package list.

torch 1.13.1
onnx 1.12.0

I tested is out from torch 1.9-2.0 thereby 1.10 should be fine.  My gut feeling is that the latest onnx 1.14 may be the root cause since the names of Gemm layer are different. Yours is Gemm_47, mine is /fc/Gemm, which might cause trouble during assigning tensors. If so, I will need to proceed a fix.
