### ISSUE TITLE
How to reproduce the experiment results on Squad in OTOV2?

### ISSUE THREAD

**Issue by jinqixiao** [tianyic/only_train_once#49]
How to reproduce the experiment results on Squad in OTOV2?

**Comment by tianyic** [comment]
@jinqixiao 

Thanks for reaching out. Those experiments were conducted based on an old (4-5 years ago) bert_squad github repo for comparison in OTOv1 2021. Since the repo was out of date and maintenance, we recently re-implemented upon [huggingface official example](https://github.com/huggingface/transformers/blob/main/examples/pytorch/question-answering/run_qa_no_trainer.py). Due to both repositories have some discrepancy, the loading checkpoint is 440M, yet the saved checkpoint becomes 416M by huggingface instead (a little weird), consequently the experimental results may have some variance. 

Here are the results of rerunning OTO on huggingface official examples. **Please use the below as the comparison reference**, which will be also included into our coming technical report.  

![image](https://github.com/tianyic/only_train_once/assets/8930611/b10d74b2-cc88-406b-812c-b7275c4510c6)

Meanwhile, I uploaded a preliminary experimental script [here](https://github.com/tianyic/only_train_once/blob/main/tutorials/02.preliminary_bert_squad.py). An official tutorial in notebook with detailed explanations will be updated next month (expected). 

For experiment, pull the latest repo, then I recommend to proceed the [sanity check over Bert](https://github.com/tianyic/only_train_once/blob/main/sanity_check/test_bert.py). Next please look into the experimental script to reproduce the results shown above. Please note that there exists [two pruning modes](https://github.com/tianyic/only_train_once/blob/c307338e070f4c111074aff3e36b1bcb08b68f13/only_train_once/operation/operator.py#L477) for multi-head attention, one along number of heads, the other for head dimension. We used number of heads here. 

Hope the above helps.
