### ISSUE TITLE
about cosine similarity, the explanations in v2 and v3, as well as HESSO, are exactly opposite. How should this be understood?

### ISSUE THREAD

**Issue by l2009312042** [tianyic/only_train_once#65]
![image](https://github.com/user-attachments/assets/df9598c8-dd00-4364-80bd-3af7ca208582)

**Comment by tianyic** [comment]
Thanks for the catch!

The discrepancy largely raised due to the ambiguity of the definition for salience scores during different periods. 

- On the time of OTOv2, the salience-score is defined to measure how redundant of each group. Therefore, redundant groups are selecting the top-K salience-scores.

- Later on, we found such definition is a bit weird, thereby changed the salience-score to measure how important of each group. This definition makes more self-explained. Consequently, the redundant groups are selecting as bottom-K salience-scores.

Cosine-similarity for later version seems indeed problematic, which not align with the latest definitions. We will upgrade our arxiv versions with that regards for clarity and consistency.

**Comment by l2009312042** [comment]
Thank you for your response. Your reply has addressed my question. The issue is now closed.
